Team-Ampersand/Dotori-server-V2

src/main/kotlin/com/dotori/v2/V2Application.kt
src/main/kotlin/com/dotori/v2/domain/member/Member.kt
src/main/kotlin/com/dotori/v2/domain/member/enums/Gender.kt
src/main/kotlin/com/dotori/v2/domain/member/enums/MassageStatus.kt
src/main/kotlin/com/dotori/v2/domain/member/enums/MusicStatus.kt
src/main/kotlin/com/dotori/v2/domain/member/enums/Role.kt
src/main/kotlin/com/dotori/v2/domain/member/enums/SelfStudyStatus.kt
src/main/kotlin/com/dotori/v2/infraStructure/config/security/SecurityConfig.kt
src/main/kotlin/com/dotori/v2/infraStructure/config/security/auth/AuthDetailService.kt
src/main/kotlin/com/dotori/v2/infraStructure/config/security/auth/AuthDetails.kt
src/main/kotlin/com/dotori/v2/infraStructure/config/security/handler/CustomAccessDeniedHandler.kt
src/main/kotlin/com/dotori/v2/infraStructure/config/security/handler/CustomAuthenticationEntryPointHandler.kt
src/main/kotlin/com/dotori/v2/infraStructure/config/security/jwt/JwtExceptionFilter.kt
src/main/kotlin/com/dotori/v2/infraStructure/config/security/jwt/JwtReqFilter.kt
src/main/kotlin/com/dotori/v2/infraStructure/config/security/jwt/TokenProvider.kt
src/main/kotlin/com/dotori/v2/infraStructure/config/web/WebConfig.kt
src/main/kotlin/com/dotori/v2/infraStructure/entity/BaseTimeEntity.kt
src/main/kotlin/com/dotori/v2/infraStructure/exception/ErrorCode.kt
src/main/kotlin/com/dotori/v2/infraStructure/exception/ErrorResponse.kt
src/main/kotlin/com/dotori/v2/infraStructure/persistence/member/MemberRepository.kt
src/test/kotlin/com/dotori/v2/V2ApplicationTests.kt

* 시큐리티 설정 추가
* 멤버 엔티티 추가
.gitkeep도 제거 했습니다.

시큐리티 설정 추가 및 멤버 엔티티추가

---

src/main/kotlin/com/dotori/v2/domain/email/domain/entity/EmailCertificate.kt
src/main/kotlin/com/dotori/v2/domain/email/presentation/EmailSendController.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/AuthController.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/dto/SignupReqDto.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/SignupServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/config/security/auth/AuthDetailService.kt
src/main/kotlin/com/dotori/v2/global/config/security/handler/CustomAccessDeniedHandler.kt
src/main/kotlin/com/dotori/v2/global/config/security/jwt/JwtExceptionFilter.kt
src/main/kotlin/com/dotori/v2/global/config/security/jwt/JwtReqFilter.kt
src/main/kotlin/com/dotori/v2/global/config/security/jwt/TokenProvider.kt
src/main/kotlin/com/dotori/v2/global/email/EmailSender.kt
src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt

:ambulance: :: 띄어쓰기 적용

---

src/main/kotlin/com/dotori/v2/domain/email/exception/EmailNotBeenException.kt
src/main/kotlin/com/dotori/v2/domain/email/exception/EmailSendFailException.kt
src/main/kotlin/com/dotori/v2/domain/email/service/impl/EmailCheckServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/email/service/impl/PasswordChangeEmailSendServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/email/service/impl/SingupEmailSendServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/member/exception/AuthKeyNotFoundException.kt
src/main/kotlin/com/dotori/v2/domain/member/exception/AuthKeyTimeOutException.kt
src/main/kotlin/com/dotori/v2/domain/member/exception/MemberAlreadyException.kt
src/main/kotlin/com/dotori/v2/domain/member/exception/MemberNotFoundException.kt
src/main/kotlin/com/dotori/v2/domain/member/exception/PasswordMismatchException.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/SignInServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/SignupServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt
src/main/kotlin/com/dotori/v2/global/error/ErrorResponse.kt
src/main/kotlin/com/dotori/v2/global/error/exception/BasicException.kt
src/main/kotlin/com/dotori/v2/global/error/handler/GlobalExceptionHandler.kt

GlobalExceptionHandler생성 및 Todo로 남아있던 에러처리를 진행하였습니다
global아래의 error폴더아래 BasicException 클래스 생성 후 다른 에러들이 상속 받아서 사용하도록 변경되었습니다 + ErrorCode의 변수명 변경

GlobalException핸들러 생성 및 에러처리 진행

---

src/main/kotlin/com/dotori/v2/domain/member/exception/MemberNotSameException.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/AuthController.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/MemberController.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/dto/req/WithdrawalReqDto.kt
src/main/kotlin/com/dotori/v2/domain/member/service/WithdrawalService.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/WithdrawalServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/config/security/SecurityConfig.kt
src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt
src/test/kotlin/com/dotori/v2/domain/member/controller/WithdrawalControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/member/service/WithdrawalServiceTest.kt

* 회원탈퇴 API 개발
* 회원탈퇴 API 개발
* memberController와 AuthController 분리
* 테스트 코드 작성

🔀 :: 14-회원탈퇴 API

---

src/main/kotlin/com/dotori/v2/domain/member/exception/TokenTypeNotValidException.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/AuthController.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/dto/res/RefreshResDto.kt
src/main/kotlin/com/dotori/v2/domain/member/service/RefreshService.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/RefreshTokenServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/config/security/jwt/TokenProvider.kt
src/test/kotlin/com/dotori/v2/domain/member/controller/RefreshTokenControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/member/service/RefreshTokenServiceTest.kt

* 리프레시 API 개발
* 리프레시 API 개발
* 테스트 코드 작성

🔀 :: 16-리프레시 API

---

src/main/kotlin/com/dotori/v2/domain/board/domain/entity/Board.kt
src/main/kotlin/com/dotori/v2/domain/board/domain/entity/BoardImage.kt
src/main/kotlin/com/dotori/v2/domain/board/domain/repository/BoardImageRepository.kt
src/main/kotlin/com/dotori/v2/domain/board/domain/repository/BoardRepository.kt
src/main/kotlin/com/dotori/v2/domain/massage/domain/entity/Massage.kt
src/main/kotlin/com/dotori/v2/domain/massage/domain/entity/MassageCount.kt
src/main/kotlin/com/dotori/v2/domain/massage/domain/repository/MassageCountRepository.kt
src/main/kotlin/com/dotori/v2/domain/massage/domain/repository/MassageRepository.kt
src/main/kotlin/com/dotori/v2/domain/music/domain/entity/Music.kt
src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt
src/main/kotlin/com/dotori/v2/domain/rule/domain/entity/RuleViolation.kt
src/main/kotlin/com/dotori/v2/domain/rule/domain/repository/RuleRepository.kt
src/main/kotlin/com/dotori/v2/domain/rule/enums/Rule.kt
src/main/kotlin/com/dotori/v2/domain/self_study/domain/entity/SelfStudy.kt
src/main/kotlin/com/dotori/v2/domain/self_study/domain/entity/SelfStudyCount.kt
src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyCountRepository.kt
src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyRepository.kt

* dotori에 필요한 엔티티를 작성했습니다
* 혹시 빼먹은 엔티티가 있으면 코멘트 달아주세요

🔀 :: 20-엔티티 생성

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/MemberController.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/dto/req/NewPasswordReqDto.kt
src/main/kotlin/com/dotori/v2/domain/member/service/ChangePasswordService.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/ChangePasswordServiceImpl.kt
src/test/kotlin/com/dotori/v2/domain/member/controller/ChangePasswordControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/member/controller/LogoutControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/member/service/ChangePasswordServiceTest.kt

* 비밀번호 변경 API 개발
* 비밀번호 변경 API 개발
* 테스트 코드 작성

🔀 :: 18-비밀번호 변경 API

---

src/main/kotlin/com/dotori/v2/domain/main_page/presentation/GetPersonalInfoController.kt
src/main/kotlin/com/dotori/v2/domain/main_page/presentation/dto/res/PersonalInfoResDto.kt
src/main/kotlin/com/dotori/v2/domain/main_page/service/GetPersonalInfoService.kt
src/main/kotlin/com/dotori/v2/domain/main_page/service/impl/GetPersonalInfoServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/config/security/SecurityConfig.kt
src/main/kotlin/com/dotori/v2/global/config/security/jwt/TokenProvider.kt
src/test/kotlin/com/dotori/v2/domain/main_page/controller/GetPersonalInfoControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/main_page/service/GetPersonalInfoServiceTest.kt

* 메인페이지에서 요청하는 유저정보 API 개발
* 테스트 코드 작성
* 메인페이지에서 요청하는 유저정보 API 개발
* accessToken에 권한 추가

🔀 :: 22-메인페이지 유저정보 API

---

src/main/kotlin/com/dotori/v2/domain/board/domain/repository/BoardRepository.kt
src/main/kotlin/com/dotori/v2/domain/board/exception/BoardNotExistsException.kt
src/main/kotlin/com/dotori/v2/domain/main_page/presentation/BoardAlarmController.kt
src/main/kotlin/com/dotori/v2/domain/main_page/presentation/dto/res/BoardAlarmResDto.kt
src/main/kotlin/com/dotori/v2/domain/main_page/service/BoardAlarmService.kt
src/main/kotlin/com/dotori/v2/domain/main_page/service/impl/BoardAlarmServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/config/security/SecurityConfig.kt
src/main/kotlin/com/dotori/v2/global/entity/BaseTimeEntity.kt
src/test/kotlin/com/dotori/v2/domain/main_page/controller/BoardAlarmControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/main_page/service/BoardAlarmServiceTest.kt

* 공지사항 알림 API 개발
* BaseTimeEntity에서 private를 제거
* 공지사항 알림 API 개발

🔀 :: 24-공지사항 알림 API

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyCountRepository.kt
src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/AlreadyApplySelfStudyException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotApplyDayException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotApplyHourException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/SelfStudyOverException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/councillor/CouncillorSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/developer/DeveloperSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/member/MemberSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/ApplySelfStudyService.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/ApplySelfStudyServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/util/FindSelfStudyCountUtil.kt
src/main/kotlin/com/dotori/v2/domain/self_study/util/SaveSelfStudyUtil.kt
src/main/kotlin/com/dotori/v2/domain/self_study/util/SelfStudyCheckUtil.kt
src/main/kotlin/com/dotori/v2/domain/self_study/util/ValidDayOfWeekAndHourUtil.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/CouncillorApplySelfStudyController.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/DeveloperApplySelfStudyController.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/MemberApplySelfStudyControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/ApplySelfStudyServiceTest.kt

* 자습신청 API 개발
* 자습신청 API 개발
* 테스트 코드 작성

🔀 :: 26-자습신청 API

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyRepository.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/councillor/CouncillorSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/developer/DeveloperSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/res/SelfStudyInfoResDto.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/res/SelfStudyMemberListResDto.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/res/SelfStudyMemberResDto.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/member/MemberSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyInfoService.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyRankService.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/ApplySelfStudyServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyInfoServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyRankServiceImpl.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/ApplySelfStudyControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyInfoControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyRankControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyInfoServiceTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyServiceTest.kt

* 자습 신청순으로 가져오는 API개발
* 테스트 코드 작성
* 자습 신청순으로 가져오는 API개발

🔀 :: 34-자습 신청순으로 가져오는 API

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/member/domain/repository/MemberRepository.kt
src/main/kotlin/com/dotori/v2/domain/self_study/dev/SelfStudyCountConfig.kt
src/main/kotlin/com/dotori/v2/domain/self_study/domain/entity/SelfStudyCount.kt
src/main/kotlin/com/dotori/v2/domain/self_study/schedule/SelfStudySchedule.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/UpdateSelfStudyStatusService.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/UpdateSelfStudyStatusServiceImpl.kt

🔀 :: 36-자습관련 스케줄 객체, util객체

---

src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyRepository.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/admin/AdminSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/councillor/CouncillorSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/developer/DeveloperSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyByMemberNameService.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByMemberNameServiceImpl.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/ApplySelfStudyControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/CancelSelfStudyControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyMemberNameControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyRankControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyMemberNameServiceTest.kt

* 이름으로 자습조회 API개발
* 테스트 코드
* API개발
* 어드민 컨트롤러

🔀 :: 43-이름으로 자습조회

---

src/main/kotlin/com/dotori/v2/domain/massage/dev/MassageCountConfig.kt
src/main/kotlin/com/dotori/v2/domain/massage/domain/entity/MassageCount.kt
src/main/kotlin/com/dotori/v2/domain/massage/domain/repository/MassageCountRepository.kt
src/main/kotlin/com/dotori/v2/domain/massage/exception/AlreadyApplyMassageException.kt
src/main/kotlin/com/dotori/v2/domain/massage/exception/SelfStudyOverException.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/ApplyMassageService.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/massage/util/FindMassageCountUtil.kt
src/main/kotlin/com/dotori/v2/domain/massage/util/MassageCheckUtil.kt
src/main/kotlin/com/dotori/v2/domain/massage/util/SaveMassageUtil.kt
src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourUtil.kt
src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt

💡 개요
* 안마의자 신청 API개발
📃 작업내용
* 안마의자 신청 API개발
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
* 테스트 코드는 나중에;;

🔀 :: 62-안마의자 신청 API개발

---

src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt
src/main/kotlin/com/dotori/v2/domain/member/domain/repository/MemberRepository.kt
src/main/kotlin/com/dotori/v2/domain/rule/presentation/admin/AdminRuleController.kt
src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/dto/RuleGrantDto.kt
src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/req/RuleGrantReqDto.kt
src/main/kotlin/com/dotori/v2/domain/rule/service/InsertRuleService.kt
src/main/kotlin/com/dotori/v2/domain/rule/service/impl/InsertRuleServiceImpl.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 규정위반 부여 기능 구현

---

src/main/kotlin/com/dotori/v2/domain/massage/domain/repository/MassageRepository.kt
src/main/kotlin/com/dotori/v2/domain/massage/exception/MassageOverException.kt
src/main/kotlin/com/dotori/v2/domain/massage/exception/NotMassageApplyDayException.kt
src/main/kotlin/com/dotori/v2/domain/massage/exception/NotMassageApplyHourException.kt
src/main/kotlin/com/dotori/v2/domain/massage/exception/NotMassageCancelDayException.kt
src/main/kotlin/com/dotori/v2/domain/massage/exception/NotMassageCancelHourException.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/CancelMassageService.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/CancelMassageServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/massage/util/FindMassageCountUtil.kt
src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt
src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourUtil.kt
src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotSelfStudyApplyDayException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotSelfStudyApplyHourException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotSelfStudyCancelDayException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotSelfStudyCancelHourException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/util/ValidDayOfWeekAndHourUtil.kt
src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt

💡 개요
* 안마의자 신청 취소 API개발
📃 작업내용
* 안마의자 신청 취소 API개발
* 네이밍 수정
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
* 테스트 코드는 나중에

🔀 :: 66-안마의자 신청 취소 API 개발

---

src/main/kotlin/com/dotori/v2/domain/massage/domain/repository/MassageRepository.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/admin/AdminMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/councillor/CouncillorMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/developer/DeveloperMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageMemberListResDto.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageMemberResDto.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/member/MemberMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/GetMassageRankService.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/GetMassageRankServiceImpl.kt

💡 개요
* 안마의자 신청한 전체 학생 조회
📃 작업내용
* 안마의자 신청한 전체 학생 조회 API개발
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 68-안마의자 신청한 학생 전체 조회

---

src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/res/SelfStudyMemberResDto.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByMemberNameServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByStuNumServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyRankServiceImpl.kt

💡 개요
* 조회할때 idx추가
📃 작업내용
* 자습신청만 idx가 필요한거 같길래 수정
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀  :: 70 - 조회할때 idx추가

---

src/main/kotlin/com/dotori/v2/domain/massage/presentation/admin/AdminMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/councillor/CouncillorMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/developer/DeveloperMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageInfoResDto.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/member/MemberMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/GetMassageInfoService.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/GetMassageInfoServiceImpl.kt

💡 개요
* 마사지 정보 조회
📃 작업내용
* 메인 페이지에서 마사지 정보 가져오는 API 개발
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 72 - 마사지 정보 조회

---

src/main/kotlin/com/dotori/v2/domain/massage/schedule/MassageSchedule.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/UpdateMassageStatusService.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/UpdateMassageStatusServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/member/domain/repository/MemberRepository.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/data/req/SignupReqDto.kt

💡 개요
* 안마의자 스케줄
📃 작업내용
* 매일 오전 2시마다 신청했거나 취소한 학생들을 신청가능하게 변경
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 77 - 안마의자 스케줄

---

src/main/kotlin/com/dotori/v2/domain/member/presentation/AuthController.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/MemberController.kt
src/main/kotlin/com/dotori/v2/domain/member/presentation/data/req/SignupReqDto.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/presentation/StuInfoController.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/presentation/data/req/SearchRequestDto.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/presentation/data/res/FindAllStudentResDto.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/presentation/data/res/SearchStudentListResDto.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/service/FindAllMemberService.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/service/SearchStudentService.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/FindAllMemberServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/SearchStudentServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/config/security/SecurityConfig.kt

💡 개요
학생정보 부분 전체조회, 검색필터링
📃 작업내용
학생정보 전체 조회 api
학생 정보를 검색 조건에 따라 필터링 된 정보를 반환하는 api 
🔀 변경사항
사감선생님, 개발자 , 기자위 전부다 사용하는 api 여서 hasAnyRole로 spring security 에 권한설정으로 변경
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

학생정보 부분 전체조회, 검색필터링

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/admin/AdminSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/councillor/CouncillorSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/developer/DeveloperSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/BanSelfStudyService.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/CancelBanSelfStudyService.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/BanSelfStudyServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/CancelBanSelfStudyServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/presentation/data/res/FindAllStudentResDto.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/FindAllMemberServiceImpl.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/ApplySelfStudyControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/CancelSelfStudyControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyInfoControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyMemberNameControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyRankControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyStuNumControllerTest.kt

💡 개요
자습금지, 자습금지취소 API
📃 작업내용
해당하는 유저 ID로 자습금지 API
해당하는 유저 ID로 자습금지해제 API
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

자습금지, 자습금지취소 API

---

src/main/kotlin/com/dotori/v2/domain/email/service/impl/EmailSendServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/email/service/impl/SignupEmailSendServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageMemberResDto.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt

💡 개요
* API명세서 적다가 이상한 부분 수정
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

 🔀 :: 90 - 리펙토링

---

src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt

💡 개요
📃 작업내용
쿼리수정
🔀 변경사항
member_music_status-> member.music
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 컬럼명이 달라 작동안하던 버그 해결

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/presentation/StuInfoController.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/presentation/data/req/ModifyStudentInfoRequest.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/service/ModifyStudentInfoService.kt
src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/ModifyStudentInfoServiceImpl.kt
src/test/kotlin/com/dotori/v2/domain/member/service/WithdrawalServiceTest.kt

💡 개요
유저 정보 수정 로직
📃 작업내용
유저 정보 요청값으로 유저 정보를 수정 가능
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 85-유저 정보 수정 로직

---

src/main/kotlin/com/dotori/v2/domain/board/domain/entity/Board.kt
src/main/kotlin/com/dotori/v2/domain/board/domain/repository/BoardRepository.kt
src/main/kotlin/com/dotori/v2/domain/board/presentation/data/dto/BoardDto.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/CreateBoardServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardDetailServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/main_page/presentation/dto/res/BoardAlarmResDto.kt
src/main/kotlin/com/dotori/v2/domain/main_page/service/impl/BoardAlarmServiceImpl.kt
src/test/kotlin/com/dotori/v2/domain/board/controller/CreateBoardControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/main_page/controller/BoardAlarmControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/main_page/service/BoardAlarmServiceTest.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 96-메인 페이지 Response 값 수정

---

src/main/kotlin/com/dotori/v2/V2Application.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

timeZone세팅

---

src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyRepository.kt
src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotSelfStudyAppliedException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/admin/AdminSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/councillor/CouncillorSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/developer/DeveloperSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/req/SelfStudyCheckReqDto.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/UpdateSelfStudyCheckService.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/UpdateSelfStudyCheckServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/ApplySelfStudyControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/CancelSelfStudyControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyInfoControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyRankControllerTest.kt

💡 개요
* 자습 체크 API개발
📃 작업내용
🔀 변경사항
* 테스트 코드
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 104 - 자습 체크 API

---

src/main/kotlin/com/dotori/v2/domain/massage/domain/entity/MassageCount.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/admin/AdminMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/councillor/CouncillorMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/developer/DeveloperMassageController.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/req/MassageLimitReqDto.kt
src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageInfoResDto.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/UpdateMassageLimitService.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/GetMassageInfoServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/UpdateMassageLimitServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/domain/entity/SelfStudyCount.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/req/SelfStudyLimitReqDto.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/res/SelfStudyInfoResDto.kt

💡 개요
* 안마의자 제한 설정을 추가
📃 작업내용
* 안마의자 제한 설정을 추가함
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 106-안마의자 제한 설정 추가

---

src/main/kotlin/com/dotori/v2/domain/rule/exception/NotFoundRuleException.kt
src/main/kotlin/com/dotori/v2/domain/rule/presentation/admin/AdminRuleController.kt
src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/dto/RuleDto.kt
src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/res/RuleListResDto.kt
src/main/kotlin/com/dotori/v2/domain/rule/presentation/data/res/RuleResDto.kt
src/main/kotlin/com/dotori/v2/domain/rule/service/DeleteRuleService.kt
src/main/kotlin/com/dotori/v2/domain/rule/service/impl/DeleteRuleServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindAdminRuleServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindAllAdminRuleServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindCouncillorServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindDeveloperRuleServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/rule/service/impl/FindMemberRuleServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 109-규정위반 삭제하기

---

src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt

💡 개요
* 안마의자 신청/취소 시간대 검증 로직이 이상함
📃 작업내용
* 신청 가능한 시간대면 return return되지 않으면 exception하게 변경
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 112 - 안마의자 신청/취소 시간대 검증 로직 변경

---

src/main/kotlin/com/dotori/v2/global/config/dev/DevMemberConfig.kt

💡 개요
* 테스트용 계정 필요
📃 작업내용
* 테스트용 계정을 만들어주는 객체 개발
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 114 - 테스트용 계정

---

DockerfileDev
DockerfileProd

💡 개요
프로필 설정 안되던 버그 해결
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 프로필 설정 안되던거 해결

---

src/main/kotlin/com/dotori/v2/global/config/dev/DevMemberConfig.kt

💡 개요
* 개발객체 비번 변경
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 118 - 게발객체 비번 변경

---

.github/workflows/ci.yml
.github/workflows/develop-cd.yml
.github/workflows/master-cd.yml

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 마스터에서만 작동해요 ㅠ

---

src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/massage/service/impl/CancelMassageServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/ApplySelfStudyServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/CancelSelfStudyServiceImpl.kt

💡 개요
* 테스트하기위해서 개발섭에 요일, 시간 검증 로직에 주석처리..
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 125 - 요일 시간 검증 로직 주석처리

---

src/main/kotlin/com/dotori/v2/domain/massage/domain/repository/MassageRepository.kt

💡 개요
* 안마의자 신청 조회에서 자습신청 조회가 됨
📃 작업내용
* repository 쿼리 수정
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
죄송합니다...

🔀 :: 127 - 안마의자 신청 조회에서 자습신청 조회가 됨

---

src/main/kotlin/com/dotori/v2/global/config/web/DevWebConfig.kt

💡 개요
* cors설정에 localhost가 들어가 있음
📃 작업내용
* cors설정분리
* 프론트 vercel url추가
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 131 - cors설정 분리

---

src/main/kotlin/com/dotori/v2/domain/massage/service/impl/GetMassageInfoServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyInfoServiceImpl.kt

💡 개요
* 예외 잘못 던지고 있었음...
📃 작업내용
* 예외 제대로 던지게 수정
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 136 - 안마의자 예외 제대로 적용

---

src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/BoardResDto.kt
src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/DetailBoardResDto.kt
src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/ListBoardResDto.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardDetailServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardsServiceImpl.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 140-공지사항 반환값 수정

---

src/main/kotlin/com/dotori/v2/domain/music/service/impl/ApplyMusicServiceImpl.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 음악신청 일요일 풀기

---

src/main/kotlin/com/dotori/v2/domain/board/domain/repository/BoardRepository.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardsServiceImpl.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 공지사항 내림차순 정렬으로 변경

---

src/main/kotlin/com/dotori/v2/domain/board/domain/entity/Board.kt
src/main/kotlin/com/dotori/v2/domain/email/domain/entity/EmailCertificate.kt
src/main/kotlin/com/dotori/v2/domain/massage/domain/entity/Massage.kt
src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/music/domain/entity/Music.kt
src/main/kotlin/com/dotori/v2/domain/rule/domain/entity/RuleViolation.kt
src/main/kotlin/com/dotori/v2/domain/self_study/domain/entity/SelfStudy.kt
src/main/kotlin/com/dotori/v2/domain/self_study/domain/entity/SelfStudyCount.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: DB 네이밍 일치

---

src/main/kotlin/com/dotori/v2/domain/music/service/impl/DeleteMusicServiceImpl.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 삭제된 유저 기상 신청 살태 신청가능으로 변경

---

src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/DeleteMusicServiceImpl.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

빠르게 머지하겠습니다

---

src/main/kotlin/com/dotori/v2/domain/main_page/service/impl/BoardAlarmServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/DeleteMusicServiceImpl.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

개발섭에서 메인서버로 적용

---

src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt

💡 개요
* 자습,안마의자 신청,취소 에러메세지가 이상함
📃 작업내용
* errorMessage수정
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 154 - 자습,안마의자 신청,취소 errorMessage 수정

---

src/main/kotlin/com/dotori/v2/domain/main_page/service/impl/BoardAlarmServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

develop -> master

---

src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/UpdateSelfStudyStatusServiceImpl.kt

💡 개요
* 자습 schedule객체가 count를 초기화 안하고 있었음
📃 작업내용
* 초기화 진행하도록 수정
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 158 - 자습 schedule객체가 count를 초기화 안하고 있었음

---

src/main/kotlin/com/dotori/v2/global/config/security/jwt/JwtReqFilter.kt

💡 개요
`JwtReqFilter`를 개선하였습니다.
📃 작업내용
1. 불필요한 중복 null 체크를 제거하여 코드를 간소화했습니다.
2. `tokenProvider`가 외부에 노출되지 않도록 `private` 접근 제한자를 추가했습니다.

JwtReqFilter 코드 개선

---

src/main/kotlin/com/dotori/v2/domain/board/presentation/admin/AdminBoardController.kt
src/main/kotlin/com/dotori/v2/domain/board/presentation/councillor/CouncillorBoardController.kt
src/main/kotlin/com/dotori/v2/domain/board/presentation/data/req/DeleteMultipleBoardReqDto.kt
src/main/kotlin/com/dotori/v2/domain/board/presentation/developer/DeveloperBoardController.kt
src/main/kotlin/com/dotori/v2/domain/board/service/DeleteMultipleBoardService.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/DeleteMultipleBoardServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/email/domain/entity/EmailCertificate.kt
src/test/kotlin/com/dotori/v2/domain/board/controller/CreateBoardControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/board/service/DeleteMultipleBoardServiceTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyServiceTest.kt

💡 개요
공지사항 일괄적으로 삭제할 수 있는 로직 추가
📃 작업내용
공지사항 id 를 리스트 형식으로 받아 일괄적으로 삭제 로직 추가
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 163-공지사항 일괄적으로 삭제할 수 있는 로직 추가

---

src/test/kotlin/com/dotori/v2/domain/member/controller/SignupControllerTest.kt

💡 개요
* AuthController의 signup테스트 코드가 없음
📃 작업내용
* 테스트 코드 추가
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 176 - signupController 테스트 코드

---

src/test/kotlin/com/dotori/v2/domain/member/service/ChangePasswordServiceTest.kt

💡 개요
* 비밀번호 변경 테스트 코드의 커버리지 높이기
📃 작업내용
* 자세한 테스트 케이스 추가
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 180 - 비밀번호 변경 테스트 코드 커버리지 높이기

---

src/test/kotlin/com/dotori/v2/domain/self_study/service/ApplySelfStudyServiceTest.kt

💡 개요
* 기존 자습신청 서비스 테스트 코드의 테스트 케이스가 부족함
📃 작업내용
* 테스트 케이스 추가
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 182 - 자습신청 서비스 테스트코드 리펙토링

---

src/test/kotlin/com/dotori/v2/domain/self_study/service/CancelSelfStudyServiceTest.kt

💡 개요
* 자습 취소 서비스 테스트 코드 리펙토링
📃 작업내용
* 테스트 케이스 추가
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 185 - 자습 취소 서비스 테스트코드 리펙토링

---

src/test/kotlin/com/dotori/v2/domain/self_study/controller/ChangeSelfStudyLimitControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/ChangeSelfStudyLimitServiceTest.kt

💡 개요
* 자습 인원변경 테스트 코드
📃 작업내용
* 자습 인원변경 컨트롤러 테스트 코드
* 자습 인원변경 서비스 테스트 코드
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 187 - 자습 인원변경 테스트 코드

---

src/test/kotlin/com/dotori/v2/domain/self_study/controller/UpdateSelfStudyCheckControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/UpdateSelfStudyCheckServiceTest.kt

💡 개요
* 자습 체크 API 테스트 코드 작성
📃 작업내용
* 자습 체크 서비스 테스트 코드 작성
* 자습 체크 컨트롤러 테스트 코드 작성
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 189 - 자습 체크 API 테스트 코드

---

src/test/kotlin/com/dotori/v2/domain/self_study/controller/BanSelfStudyControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/BanSelfStudyServiceTest.kt

💡 개요
* 자습 금지 API 테스트 코드 작성
📃 작업내용
* 자습 금지 서비스 테스트 코드 작성
* 자습 금지 컨트롤러 테스트 코드 작성
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 191 - 자습 금지 테스트 코드 작성

---

src/test/kotlin/com/dotori/v2/domain/self_study/service/UpdateSelfStudyStatusServiceTest.kt

💡 개요
* 자습 상태를 일괄적으로 변경하는 서비스 테스트코드 작성
📃 작업내용
* 자습 상태를 일괄적으로 변경하는 서비스 테스트코드 작성
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 193 - 자습 상태를 일괄적으로 변경하는 서비스 테스트 코드

---

src/main/kotlin/com/dotori/v2/domain/massage/util/MassageCheckUtil.kt
src/main/kotlin/com/dotori/v2/domain/rule/service/impl/DeleteRuleServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/exception/AlreadyApplySelfStudyException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/exception/NotAppliedException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/exception/NotSelfStudyAppliedException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/exception/NotSelfStudyApplyDayException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/exception/NotSelfStudyApplyHourException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/exception/NotSelfStudyCancelDayException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/exception/NotSelfStudyCancelHourException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/exception/SelfStudyOverException.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/admin/AdminSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/councillor/CouncillorSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/developer/DeveloperSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/req/SelfStudySearchReqDto.kt
src/main/kotlin/com/dotori/v2/domain/self_study/presentation/member/MemberSelfStudyController.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyByStuNumAndNameService.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/ApplySelfStudyServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByStuNumAndNameServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyInfoServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/UpdateSelfStudyCheckServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/self_study/util/SelfStudyCheckUtil.kt
src/main/kotlin/com/dotori/v2/domain/self_study/util/ValidDayOfWeekAndHourUtil.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/ApplySelfStudyServiceTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/CancelSelfStudyServiceTest.kt
src/test/kotlin/com/dotori/v2/domain/self_study/service/UpdateSelfStudyCheckServiceTest.kt

💡 개요
폴더 위치 변경
📃 작업내용
exception 오타 해결
dto가 exception에 있어 파일 이동
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 195-폴더 위치 변경

---

.github/CODEOWNERS

💡 개요
* 코드 오너 설정
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 197 - codeowners 세팅

---

src/test/kotlin/com/dotori/v2/domain/self_study/util/FindSelfStudyCountUtilTest.kt

💡 개요
* FindSelfStudyCountUtil 테스트 코드 작성
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 199 - FindSelfStudyCountUtil 테스트 코드 작성

---

src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt

💡 개요
* 20분부터 신청가능하게 수정가능하게 수정
📃 작업내용
* ValidDayOfWeekAndHourMassageUtil 조건문 수정
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 201 - 20분부터 신청가능하도록 수정

---

src/test/kotlin/com/dotori/v2/domain/self_study/util/SelfStudyCheckUtilTest.kt

💡 개요
* SelfStudyCheckUtil 테스트 코드 작성
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 ::205 - SelfStudyCheckUtil 테스트 코드 작성

---

src/test/kotlin/com/dotori/v2/domain/board/util/BoardUtil.kt
src/test/kotlin/com/dotori/v2/domain/email/util/EmailCertificateUtil.kt
src/test/kotlin/com/dotori/v2/domain/massage/util/MassageUtil.kt
src/test/kotlin/com/dotori/v2/domain/member/util/MemberUtil.kt
src/test/kotlin/com/dotori/v2/domain/music/util/MusicUtil.kt
src/test/kotlin/com/dotori/v2/domain/rule/util/RuleViolationUtil.kt
src/test/kotlin/com/dotori/v2/domain/self_study/util/SelfStudyUtil.kt

💡 개요
DI주입 받을 필요 없으니, 그냥 companion으로 변경했습니다.

🔀 :: test domain을 companion object 로 변경

---

src/test/kotlin/com/dotori/v2/domain/main_page/service/GetPersonalInfoServiceTest.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 209 - 서비스 테스트 코드에 util 적용

---

src/main/kotlin/com/dotori/v2/domain/self_study/util/ValidDayOfWeekAndHourUtil.kt
src/test/kotlin/com/dotori/v2/domain/self_study/util/ValidaDayOfWeekAndHourTest.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 자습신청 일요일 검증 로직 제거

---

src/test/kotlin/com/dotori/v2/domain/massage/controller/MassageApplyControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/massage/service/MassageApplyServiceTest.kt

💡 개요
* 안마의자 신청 테스트 코드 작성
📃 작업내용
* 서비스 테스트 코드
* 컨트롤러 테스트 코드
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 216 - 안마의자 신청 테스트 코드

---

src/test/kotlin/com/dotori/v2/domain/massage/controller/GetMassageInfoControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/massage/service/GetMassageInfoServiceTest.kt

💡 개요
* 안마의자 정보 테스트 코드
📃 작업내용
* 컨트롤러 테스트 코드
* 서비스 테스트 코드
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 218 - 안마의자 정보 테스트

---

src/test/kotlin/com/dotori/v2/domain/massage/controller/UpdateMassageLimitControllerTest.kt
src/test/kotlin/com/dotori/v2/domain/massage/service/UpdateMassageLimitServiceTest.kt

💡 개요
* 안마의자 제한 수정 테스트 코드 작성
📃 작업내용
* 서비스 테스트 코드
* 컨트롤러 테스트 코드
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀  :: 221 - 안마의자 제한수 수정 테스트 코드

---

src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt

💡 개요
* 21분부터 안마의자 취소가 됨
📃 작업내용
🔀 변경사항
* 조건문 간단하게 수정
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔨 :: 223 - 조건문에서 잘못 검사하고 있던 부분 수정

---

buildSrc/src/main/kotlin/Dependencies.kt

💡 개요
* jwt 의존성이 buildSrc에 잘못 적혀있던 부분 수정
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🛠️  :: jwt 의존성 수정

---

buildSrc/src/main/kotlin/Dependencies.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

개발 브랜치를 마스터브랜치에 머지

---

src/main/kotlin/com/dotori/v2/domain/self_study/util/ValidDayOfWeekAndHourUtil.kt

💡 개요
* 일요일에 자습신청, 취소가 되면 안됨
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 233 - 일요일에 자습신청, 취소가 되면 안됨

---

src/main/kotlin/com/dotori/v2/domain/main_page/presentation/dto/res/BoardAlarmResDto.kt
src/main/kotlin/com/dotori/v2/domain/main_page/service/impl/BoardAlarmServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/massage/dev/MassageCountConfig.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/RefreshTokenServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/SignInServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/config/dev/DevMemberConfig.kt
src/main/kotlin/com/dotori/v2/global/security/SecurityConfig.kt
src/main/kotlin/com/dotori/v2/global/security/auth/AuthDetailService.kt
src/main/kotlin/com/dotori/v2/global/security/auth/AuthDetails.kt
src/main/kotlin/com/dotori/v2/global/security/handler/CustomAccessDeniedHandler.kt
src/main/kotlin/com/dotori/v2/global/security/handler/CustomAuthenticationEntryPointHandler.kt
src/main/kotlin/com/dotori/v2/global/security/jwt/JwtExceptionFilter.kt
src/main/kotlin/com/dotori/v2/global/security/jwt/JwtReqFilter.kt
src/main/kotlin/com/dotori/v2/global/security/jwt/TokenProvider.kt
src/main/kotlin/com/dotori/v2/global/util/UserUtil.kt
src/test/kotlin/com/dotori/v2/domain/member/service/RefreshTokenServiceTest.kt
src/test/kotlin/com/dotori/v2/domain/member/service/SignInServiceTest.kt

💡 개요
massage count config 메서드명 변경
security 관련 클래스 패키지 global로 이동
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

239 chore/massagecountconfig method

---

src/main/kotlin/com/dotori/v2/domain/board/presentation/data/dto/BoardDto.kt
src/main/kotlin/com/dotori/v2/domain/board/presentation/data/dto/BoardImageDto.kt
src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/BoardResDto.kt
src/main/kotlin/com/dotori/v2/domain/board/presentation/data/res/DetailBoardResDto.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/CreateBoardServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/DeleteBoardServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/DeleteMultipleBoardServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardDetailServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/board/service/impl/GetBoardsServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/main_page/service/impl/BoardAlarmServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/thirdparty/aws/s3/AwsS3Config.kt
src/main/kotlin/com/dotori/v2/global/thirdparty/aws/s3/S3Service.kt
src/main/kotlin/com/dotori/v2/global/thirdparty/aws/s3/S3ServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/thirdparty/aws/ses/AwsSesConfig.kt
src/test/kotlin/com/dotori/v2/domain/board/service/DeleteMultipleBoardServiceTest.kt
src/test/kotlin/com/dotori/v2/domain/main_page/service/BoardAlarmServiceTest.kt

💡 개요
BoardImage 엔티티를 반환하던 BoardService를 Dto로 반환하도록 수정했습니다
📃 작업내용
BoardImageDto 추가
Board 관련 Dto를 생성할때 of 함수를 사용하여 생성하도록 수정
dto 내부 함수가 추가됨에따라 서비스 로직도 수정되었습니다.
추가로 s3, ses 관련 클래스들을 thirdparty 패키지로 이동시켰습니다.
🔀 변경사항
- BoardResDto
- BoardDto
- DetailsBoardResDto
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

241 refactor/board image dto

---

src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyRepository.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByStuNumAndNameServiceImpl.kt

💡 개요
죄송합니다
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

add :: self study 조건 추가

---

.github/workflows/develop-cd.yml
.github/workflows/master-cd.yml

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

 :: CICD Docker 안돼던 이슈 해결

---

.github/workflows/master-cd.yml

💡 개요
📃 작업내용
🔀 변경사항
뒤에 있던 --platform 을 제거 안해서 제거 하였습니다
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 진짜 고쳤습니다

---

src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyRepository.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByStuNumAndNameServiceImpl.kt

💡 개요
selfstudy member를 하나하나 find하는 것이 아닌 in 문으로 포함된 멤버만 찾게 수정했습니다.
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

fix :: 자습 필터 검색 로직 수정

---

src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyRepository.kt
src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByStuNumAndNameServiceImpl.kt

💡 개요
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

develop 변경사항 master로 병합 

---

src/main/kotlin/com/dotori/v2/domain/member/presentation/data/req/NewPasswordReqDto.kt
src/test/kotlin/com/dotori/v2/domain/member/controller/ChangePasswordControllerTest.kt

💡 개요
* 로그인시 비번변경 Request에 있던 email 컬럼 제거
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
~~진짜 왜 있음...?~~

🛠️  :: 255 - NewPasswordReqDto email 컬럼 제거

---

src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepositoryImpl.kt

💡 개요
- 유저 검색 기능을 수정했습니다.
📃 작업내용
🔀 변경사항
- 모든 단어가 일치해야 결과를 반환하는 방식에서 1글자 이상이 포함될 시 결과를 반환해주는 방식으로 검색 로직을 수정했습니다.
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타

🔀 :: 검색 기능 수정

---

src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageMemberResDto.kt
src/main/kotlin/com/dotori/v2/domain/selfstudy/presentation/dto/res/SelfStudyMemberResDto.kt
src/main/kotlin/com/dotori/v2/domain/student/presentation/data/res/FindAllStudentResDto.kt
src/main/kotlin/com/dotori/v2/domain/student/presentation/data/res/SearchStudentListResDto.kt
src/main/kotlin/com/dotori/v2/domain/student/service/impl/FindAllMemberServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/student/service/impl/SearchStudentServiceImpl.kt

💡 개요
+ 학생 정보 반환 dto 수정
📃 작업내용
+ 학생 정보를 반환하는 dto에 `profileImage` 필드를 추가하였습니다.
🔀 변경사항
+ 자습, 안마의자에서 학생정보를 반환하는 dto에서 `profileUrl` 필드명을 `profileImage`로 변경하였습니다.

279 학생 정보 반환 dto 수정

---

build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
docker-compose.yml

💡 개요
모니터링 환경좀 세팅했습니다. 관련 구성 파일은 디스코드 확인해주시고
yml 변동사항은 다음과같은 정보 추가해줘야합니다. dev prod 전부 동일
```yml
management:
endpoints:
web:
exposure:
include: prometheus
```

프로메테우스, 그라파나 세팅

---

docker-compose.yml

actuator path security 설정이 아니라 actuator만 다른 포트에 띄우도록 하겠습니다.
도커 네트워크 설정만 해줬네요 작업 내용은

add :: docker networks set

---

src/main/kotlin/com/dotori/v2/domain/health/HealthCheckController.kt
src/main/kotlin/com/dotori/v2/global/security/SecurityConfig.kt

💡 개요
+ Health Check를 위한 Controller 생성
📃 작업내용
+ HealthCheckConroller를 생성하였습니다.

290 HealthCheckController

---

.github/workflows/ci.yml
.github/workflows/dotori-develop-cd.yml
.github/workflows/master-cd.yml
build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
src/main/resources/logback-spring.xml

308 loki logbacks

---

src/main/kotlin/com/dotori/v2/aop/HttpLoggingAspect.kt

💡 개요
+ HTTP request logging aop
📃 작업내용
+ HTTP request logging aop를 추가하였습니다.

312 :: HTTP request logging aop

---

src/main/kotlin/com/dotori/v2/aop/HttpLoggingAspect.kt

📃 작업내용
+ develop 브랜치를 master브랜치에 적용시키겠습니다.

develop 브랜치 master 브랜치 머지

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/DeleteProfileImageServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/UpdateProfileImageServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/UploadProfileImageServiceImpl.kt

💡 개요
+ 프로필 이미지를 수정하면 자습상태가 초기화되는 에러가 발생했습니다.

315 update profile image method

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepositoryImpl.kt

310 학생 검색 API 쿼리개선, 인덱스 적용

---

src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepositoryImpl.kt
src/main/kotlin/com/dotori/v2/domain/selfstudy/presentation/dto/res/SelfStudyMemberResDto.kt
src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/GetSelfStudyInfoServiceImpl.kt

329 hotfix/user search condition

---

buildSrc/src/main/kotlin/DependencyVersions.kt
src/main/kotlin/com/dotori/v2/global/error/ErrorFilter.kt
src/main/kotlin/com/dotori/v2/global/security/SecurityConfig.kt

ErrorFilter, jjwt version 호환성 문제 해결

---

src/main/resources/junit-platform.properties

💡 개요
+ Junit 테스트때문에 빌드시간이 오래걸립니다.
📃 작업내용
+ `junit-platform.properties` 파일을 작성하였습니다.

Junit Service,Controller 병렬테스트

---

src/main/kotlin/com/dotori/v2/domain/member/domain/repository/MemberRepository.kt
src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/ApplyMusicServiceImpl.kt
src/test/kotlin/com/dotori/v2/domain/music/service/ApplyMusicServiceTest.kt

💡 개요
음악 신청했을 때 중복 신청이 되는 경우가 있었습니다
📃 작업내용
- 음악 신청 동시성 문제 해결

음악 신청 동시성 핸들링

---

src/main/kotlin/com/dotori/v2/V2Application.kt
src/main/kotlin/com/dotori/v2/domain/student/service/impl/ModifyStudentInfoServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/config/redis/service/RedisCacheService.kt
src/test/kotlin/com/dotori/v2/domain/music/service/ApplyMusicServiceTest.kt

어드민 유저 업데이트 api 캐시 업데이트 기능 추가

---

src/main/kotlin/com/dotori/v2/global/error/ErrorFilter.kt
src/main/kotlin/com/dotori/v2/global/security/SecurityConfig.kt
src/main/kotlin/com/dotori/v2/global/security/jwt/TokenProvider.kt

💡 개요
+ 예외처리 할때 무조건 500이 반환되는 문제를 해결했습니다.
📃 작업내용
+ ErrorFilter 클래스에 `JwtException`, `ExpiredJwtException`, `IllegalArgumentException` 등의 예외를 추가하였습니다.
🔀 변경사항
+ ErrorFilter 클래스를 SecurityConfig Custom Filter로 등록하였습니다.

#387 update/token exception

---

src/main/kotlin/com/dotori/v2/aop/HttpLoggingAspect.kt

chore :: logging aspect substring

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/member/service/impl/UpdateProfileImageServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/util/ProfileImageService.kt

💡 개요
member 로직 리팩토링을 했습니다.
📃 작업내용
member 엔티티에 프로필 이미지 여부 반환해주는 내부 함수를 만들어 리팩토링하였습니다.

refactor :: imageUpload refactor

---

src/main/kotlin/com/dotori/v2/domain/music/presentation/admin/AdminMusicController.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/councillor/CouncillorMusicController.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/data/res/MusicRankResDto.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/developer/DeveloperMusicController.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/member/MemberMusicController.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/FindMusicRankServiceImpl.kt

💡 개요
음악 조회할때 유저가 해당 음악에 좋아요를 눌렀는지 안눌렀는지 판단하기 위한 필드를 추가했습니다.
📃 작업내용
- 필드추가
- 반환값 void -> MusicLikeCountResDto

Music 조회할 때 좋아요 유무 반환

---

src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/FindMusicRankServiceImpl.kt

update :: find music rank desc

---

src/main/kotlin/com/dotori/v2/domain/music/domain/entity/Music.kt
src/main/kotlin/com/dotori/v2/domain/music/domain/entity/MusicLike.kt
src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicLikeRepository.kt
src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt
src/main/kotlin/com/dotori/v2/domain/music/exception/NotValidMusicLikeException.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/admin/AdminMusicController.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/councillor/CouncillorMusicController.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/data/res/MusicLikeCountResDto.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/data/res/MusicRankListResDto.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/data/res/MusicRankResDto.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/data/res/MusicResDto.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/developer/DeveloperMusicController.kt
src/main/kotlin/com/dotori/v2/domain/music/presentation/member/MemberMusicController.kt
src/main/kotlin/com/dotori/v2/domain/music/service/FindMusicRankService.kt
src/main/kotlin/com/dotori/v2/domain/music/service/ToggleMusicLikeService.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/ApplyMusicServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/FindMusicRankServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/FindMusicsServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/ToggleMusicLikeServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/config/redis/service/RedisCacheService.kt
src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt

💡 개요
revert 된 좋아요 관련 기능을 다시 구현했습니다
📃 작업내용
- 좋아요 누르기 / 취소하기
- 좋아요 랭킹 순으로 조회
- 음악 신청 순으로 조회에 필드 추가

좋아요 부분 관련 기능

---

src/main/kotlin/com/dotori/v2/domain/auth/service/impl/SignInEmailAndPasswordServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicLikeRepository.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/DeleteMusicServiceImpl.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/DeleteMyMusicServiceImpl.kt

💡 개요
음악 삭제시 연관된 좋아요 데이터까지 함께 삭제
📃 작업내용
음악 삭제시 연관된 좋아요 함께 삭제하는 코드가 아래 서비스에 추가되었습니다.
- MusicDeleteService
- MyMusicDeleteServce

add :: music like delete;

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/indicator/ReservationIndicatorAspect.kt

index 관련 설정을 db에 직접 접근해 설정해놓기 때문에 불필요한 부분을 제거합니다

454 dotori member index

---

src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicLikeRepository.kt
src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt
src/main/kotlin/com/dotori/v2/domain/music/service/impl/ToggleMusicLikeServiceImpl.kt
src/main/kotlin/com/dotori/v2/global/config/redis/service/RedisCacheService.kt

💡 개요
음악 좋아요 동시성 문제 해결, music cache ttl set

459 hotfix/music like cache ttl

---

src/main/kotlin/com/dotori/v2/domain/member/domain/entity/Member.kt
src/main/kotlin/com/dotori/v2/domain/student/presentation/StuInfoController.kt
src/main/kotlin/com/dotori/v2/domain/student/task/SyncStudentNumberTask.kt

csv파일은 전교부에게 `학생이메일|최신학번` 포멧으로 요청하여 받자

csv로 학번 싱크

---

buildSrc/src/main/kotlin/Dependencies.kt
src/main/kotlin/com/dotori/v2/V2Application.kt
src/main/kotlin/com/dotori/v2/domain/massage/schedule/MassageNotificationSchedule.kt
src/main/kotlin/com/dotori/v2/domain/massage/schedule/MassageSchedule.kt
src/main/kotlin/com/dotori/v2/domain/selfstudy/schedule/SelfStudyNotificationSchedule.kt
src/main/kotlin/com/dotori/v2/domain/selfstudy/schedule/SelfStudySchedule.kt
src/main/kotlin/com/dotori/v2/domain/student/task/SyncStudentNumberTask.kt
src/main/kotlin/com/dotori/v2/global/config/config/RestTemplateConfig.kt
src/main/kotlin/com/dotori/v2/global/webhook/client/DiscordClient.kt
src/main/kotlin/com/dotori/v2/global/webhook/client/DiscordClientImpl.kt
src/main/kotlin/com/dotori/v2/global/webhook/protocol/DiscordSendMessage.kt

서버 재배포, 자습, 안마의자 기록, 학번 동기화에 작성됨
추가적으로 더필요하면 discord client 사용해서 알림기능 넣을 수 있음.

478 feature/discord webhook
