src/main/kotlin/com/dotori/v2/domain/email/domain/entity/EmailCertificate.kt, src/main/kotlin/com/dotori/v2/domain/email/domain/repository/EmailCertificateRepository.kt, src/main/kotlin/com/dotori/v2/domain/email/presentation/EmailSendController.kt, src/main/kotlin/com/dotori/v2/domain/email/service/impl/EmailCheckServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/email/service/impl/EmailSendServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/SignupServiceImpl.kt
* 기존 이메일 인증 로직은 인증된후 emailCertificate를 제거해서 회원가입시에 emailCertificate가 없으면 회원가입을 진행하는 방식임
* 위의 방식으로 진행하면 메일 인증을 안하고 요청을 보내도 회원가입이 성공함
* 그래서 emailCertificate의 authentication을 확인해서 회원가입을 진행하도록 수정
#6
=> 이메일 인증로직 수정

src/main/kotlin/com/dotori/v2/domain/self_study/domain/repository/SelfStudyRepository.kt, src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotAppliedException.kt, src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotCancelDayException.kt, src/main/kotlin/com/dotori/v2/domain/self_study/excetpion/NotCancelHourException.kt, src/main/kotlin/com/dotori/v2/domain/self_study/presentation/councillor/CouncillorSelfStudyController.kt, src/main/kotlin/com/dotori/v2/domain/self_study/presentation/developer/DeveloperSelfStudyController.kt, src/main/kotlin/com/dotori/v2/domain/self_study/presentation/member/MemberSelfStudyController.kt, src/main/kotlin/com/dotori/v2/domain/self_study/service/CancelSelfStudyService.kt, src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/ApplySelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/CancelSelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/self_study/util/SelfStudyCheckUtil.kt, src/main/kotlin/com/dotori/v2/domain/self_study/util/ValidDayOfWeekAndHourUtil.kt, src/test/kotlin/com/dotori/v2/domain/self_study/controller/ApplySelfStudyControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/self_study/controller/CancelSelfStudyControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/self_study/controller/GetSelfStudyRankControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/self_study/service/ApplySelfStudyServiceTest.kt, src/test/kotlin/com/dotori/v2/domain/self_study/service/CancelSelfStudyServiceTest.kt
* 자습신청 취소 API 개발
* 자습신청 취소 API
* 테스트 코드
* util객체의 메서드 네이밍 수정
=> 🔀 :: 31-자습신청 취소 API

src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt
💡 개요
* 최대 인원을 유동적으로 변경할 수 있게끔 했으니까 메세지도 그에 맞게 수정함
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
=> 🔀 :: 161 - 자습, 안마의자 신청인원이 유동적으로 변할 수 있어서 에러 메세지 수정

src/main/kotlin/com/dotori/v2/domain/member/presentation/data/req/NewPasswordReqDto.kt, src/main/kotlin/com/dotori/v2/domain/member/presentation/data/req/NoAuthNewPasswordReqDto.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/ChangePasswordServiceImpl.kt, src/test/kotlin/com/dotori/v2/domain/member/controller/ChangePasswordControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/member/service/ChangePasswordServiceTest.kt
💡 개요
* 로그인 하기전 비번변경에선 현재 비밀번호 입력 안받게 수정해달라해서 수정.
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
=> 🔀 :: 로그인 되지 않았을때 비번병경할때 현재 비밀번호를 입력하지 않고 변경하게끔 수정

src/main/kotlin/com/dotori/v2/domain/email/domain/entity/EmailCertificate.kt
💡 개요
157-이메일 인증 번호 보내는 500 에러 해결
📃 작업내용
기존 DB와 Entity 구성이 달라 컬럼 구성 변경(Aws내에서 작업함)
🔀 변경사항
기존 ManyToOne member로 식별 하지 않고 authentication 컬럼으로 구별하기 때문에 기존 Email_certificate 테이블이 변경됌
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
=> 🔀 :: 157-이메일 인증 번호 보내는 500 에러 해결

src/main/kotlin/com/dotori/v2/domain/music/service/impl/DeleteMyMusicServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/self_study/presentation/admin/AdminSelfStudyController.kt, src/main/kotlin/com/dotori/v2/domain/self_study/presentation/councillor/CouncillorSelfStudyController.kt, src/main/kotlin/com/dotori/v2/domain/self_study/presentation/developer/DeveloperSelfStudyController.kt, src/main/kotlin/com/dotori/v2/domain/self_study/presentation/member/MemberSelfStudyController.kt, src/main/kotlin/com/dotori/v2/domain/self_study/service/GetSelfStudyByStuNumAndNameService.kt, src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByStuNumAndNameServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/stu_info/exception/SelfStudySearchReqDto.kt, src/main/kotlin/com/dotori/v2/domain/stu_info/presentation/data/req/SearchRequestDto.kt, src/main/kotlin/com/dotori/v2/domain/stu_info/presentation/data/res/SearchStudentListResDto.kt, src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/SearchStudentServiceImpl.kt
💡 개요
학생정보 자습 상태 응답값 변경 및 검색 필터 로직 개선
📃 작업내용
1. 학생정보에서 자습신청 상태값을 응답값으로 보내주던것을 -> 해당 멤버 자체 자습상태 응답 값으로 변경
2. 자습신청 검색 필터에서 불필요한 request 부분 및 로직 개선
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
=> 학생정보 자습 상태 응답값 변경 및 검색 필터 로직 개선

src/main/kotlin/com/dotori/v2/domain/self_study/util/ValidDayOfWeekAndHourUtil.kt, src/test/kotlin/com/dotori/v2/domain/self_study/util/ValidaDayOfWeekAndHourTest.kt
💡 개요
* 자습신청 시간 검증 객체 테스트 코드 작성
📃 작업내용
* 자습신청 시간 검증 객체 테스트 코드 작성
🔀 변경사항
* 자습신청 시간 검증 객체의 테스트를 위해 생성자에서 LocalDateTime을 변경할 수 있게끔 수정
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
=> 🔀 :: 203 - 자습신청 시간 검증 객체 테스트 코드

build.gradle.kts, src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepository.kt, src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepositoryImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/domain/repository/MemberRepository.kt, src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/FindAllMemberServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/stu_info/service/impl/SearchStudentServiceImpl.kt, src/main/kotlin/com/dotori/v2/global/config/querydsl/QueryDSLConfig.kt
💡 개요
유저 동적 검색 서비스 QueryDSL를 적용하여 리팩터링하였습니다.
📃 작업내용
where 조건절에 바로 BooleanExpression을 넣을 수도 있었지만 이번에는
더욱 직관적이고 조립하여 재사용성도 높여지는 where 조건문에 들어가는 함수를 분리해서 작성했습니다.
🔀 변경사항
- `SearchStudentServiceImpl` 비즈니스로직
- `CustomMemberRepository`쿼리문 작성
🙋‍♂️ 질문사항
궁금한게 검색조건을 받을때 role, gender는 왜 String?으로 받는지 궁금합니다. 그냥 Enum으로 받아도 상관 없을거 같은데..
🍴 사용방법
🎸 기타
향후 자습신청 멤버 검색 api도 바로 적용하겠습니다 QueryDSL
=> #229 유저 검색 서비스 QueryDSL 적용

.github/CODEOWNERS, src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepository.kt, src/main/kotlin/com/dotori/v2/domain/member/domain/repository/CustomMemberRepositoryImpl.kt, src/main/kotlin/com/dotori/v2/domain/self_study/service/impl/GetSelfStudyByStuNumAndNameServiceImpl.kt
💡 개요
자습 신청 멤버 동적 검색 서비스에도 QueryDSL을 적용했습니다.
조건절을 함수로 분리했기때문에 self study member를 찾는 쿼리도 전에 만들어놓은 함수를 이용해 개발했습니다.
📃 작업내용
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
=> 237 feat/get self study querydsl

src/main/kotlin/com/dotori/v2/domain/member/presentation/MemberController.kt, src/main/kotlin/com/dotori/v2/domain/member/service/WithdrawalService.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/WithdrawalServiceImpl.kt, src/test/kotlin/com/dotori/v2/domain/member/controller/WithdrawalControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/member/service/WithdrawalServiceTest.kt
💡 개요
* @baekteun  탈퇴할때 이메일, 비번 입력 앋받게 수정해주라 하셔서 작업함
📃 작업내용
* UserController.withdrawal(), WithdrawalService에서 이메일, 비밀번호 입력 안받게 수정
🔀 변경사항
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
=> 🔨  ::  243 - 회원탈퇴할때 이메일, 비밀번호 입력 안받게 수정

src/main/kotlin/com/dotori/v2/domain/main_page/presentation/dto/res/PersonalInfoResDto.kt, src/main/kotlin/com/dotori/v2/domain/member/presentation/MemberController.kt, src/main/kotlin/com/dotori/v2/domain/member/service/UpdateProfileImageService.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UpdateProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UploadProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/global/thirdparty/aws/s3/S3ServiceImpl.kt, src/test/kotlin/com/dotori/v2/domain/main_page/controller/GetPersonalInfoControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/member/controller/ChangePasswordControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/member/controller/LogoutControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/member/controller/WithdrawalControllerTest.kt
💡 개요
+ 프로필 이미지 수정하는 api를 구현하겠습니다.
📃 작업내용
+ 프로필 이미지 수정하는 service를 구현하겠습니다.
+ 프로필 이미지 수정하는 api를 추가하였습니다.
+ home 화면에서 반환되는 유저정보에 profileImage필드를 추가하였습니다.
+ db에 프로필이미지 저장할때 string이 아닌 이미지 url로 저장하도록 수정하였습니다.
=> 🔀 :: 프로필 이미지 수정 api

src/main/kotlin/com/dotori/v2/domain/massage/presentation/dto/res/MassageMemberResDto.kt, src/main/kotlin/com/dotori/v2/domain/member/presentation/MemberController.kt, src/main/kotlin/com/dotori/v2/domain/member/service/DeleteProfileImageService.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/DeleteProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UploadProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/self_study/presentation/dto/res/SelfStudyMemberResDto.kt, src/test/kotlin/com/dotori/v2/domain/member/controller/ChangePasswordControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/member/controller/LogoutControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/member/controller/WithdrawalControllerTest.kt
💡 개요
+ 프로필 이미지 삭제 기능 구현하였습니다.
📃 작업내용
+ 프로필 이미지 삭제 service 구현하였습니다.
+ 프로필 이미지 삭제 api 구현하였습니다.
+ 안마의자, 자습 list 필드 추가하였습니다.
🔀 변경사항
+ 안마의자, 자습 list 필드에 profileUrl을 추가하였습니다.
+ param이름을 단일형으로 변경하였습니다.
🙋‍♂️ 질문사항
🍴 사용방법
🎸 기타
=> 🔀 :: 프로필 이미지 삭제 api

src/main/kotlin/com/dotori/v2/domain/auth/presentation/data/res/RefreshResDto.kt, src/main/kotlin/com/dotori/v2/domain/auth/presentation/data/res/SignInResDto.kt, src/main/kotlin/com/dotori/v2/domain/auth/service/impl/RefreshTokenServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/auth/service/impl/SignInEmailAndPasswordServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/auth/service/impl/SignInGAuthServiceImpl.kt, src/test/kotlin/com/dotori/v2/domain/member/controller/RefreshTokenControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/member/controller/SignInControllerTest.kt, src/test/kotlin/com/dotori/v2/domain/member/service/RefreshTokenServiceTest.kt, src/test/kotlin/com/dotori/v2/domain/member/service/SignInServiceTest.kt, src/test/kotlin/com/dotori/v2/testUtil/AuthDataUtil.kt
💡 개요
+ 토큰을 반환하는 response에 필드 추가
📃 작업내용
+ `RefreshResDto` , `SignInResDto`에 roles라는 필드를 추가하였습니다.
🙋‍♂️ 질문사항
+ `expiresAt` 이라는 필드도 함께 반환해달라고 요청하셨는데 이미 각 Dto들에서 `expiresAt`에서 반환하는 accessToken의 만료기간을 반환해줘서 일단을 추가시키지 않았습니다. 혹시 현재 dto에서 `expiresAt`필드가 추가로 필요하다면 말씀해주세요.
=> 277 token response 필드 추가

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt
💡 개요
개발서버 mysql 컨테이너로 디비 이전했는데 driver class name을 못 읽더라고요
mysql connector 의존성이 없어서 그런 것 같습니다.
=> add :: mysql connector dependency

src/main/kotlin/com/dotori/v2/global/config/dev/DevMemberConfig.kt
💡 개요
중복된 pk의 유저 데이터를 저장하기 때문에 오류가 발생하여 exists문을 사용하여 해당 아이디의 엔티티가 존재하지 않을때만 데이터를 삽입하게 만들었습니다.
📃 작업내용
- 중복 유저 확인
=> fix :: exist member

appspec.yml, src/main/kotlin/com/dotori/v2/domain/massage/service/impl/ApplyMassageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/ApplySelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/indicator/Indicate.kt, src/main/kotlin/com/dotori/v2/indicator/IndicatorTarget.kt, src/main/kotlin/com/dotori/v2/indicator/ReservationCategory.kt, src/main/kotlin/com/dotori/v2/indicator/ReservationIndicatorAspect.kt, src/main/kotlin/com/dotori/v2/indicator/ReservationIndicators.kt, src/main/kotlin/com/dotori/v2/indicator/ReservationIndicatorsRepository.kt, src/main/kotlin/com/dotori/v2/indicator/ResultStatus.kt
8 ~ 9시 열리는 reservation api에 대한 request time, response time, latency 지표 정보들을 disk에 저장하는 기능을 개발했습니다.
\+ 현재는 request가 올 때마다 entity를 save합니다. 하나하나 세이브를 하지 말고 buffer에 담아뒀다가 한번에 flush하는 방법도 괜찮을 듯 싶습니다.
> 1.차후 조회하는 api에서 latency 별로 sort할지 request time별로 sort할지에 대한 여부도 체크해야합니다.
> 2. 테스트를 작성해야합니다. aop 시나리오를 제대로 테스트할 방법을 찾아야합니다.
=> #342 예약 api 지표 분석, 저장 기능 개발

src/main/kotlin/com/dotori/v2/domain/auth/service/impl/SignUpServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/DeleteProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UpdateProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UploadProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/WithdrawalServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/ApplySelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/BanSelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/CancelBanSelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/CancelSelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/student/presentation/data/res/FindAllStudentResDto.kt, src/main/kotlin/com/dotori/v2/domain/student/service/impl/FindAllMemberServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/student/service/impl/ModifyStudentInfoServiceImpl.kt, src/main/kotlin/com/dotori/v2/global/config/RedisCacheConfig.kt, src/main/kotlin/com/dotori/v2/global/config/redis/service/RedisCacheService.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/ApplySelfStudyServiceSynchronicityTest.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/ApplySelfStudyServiceTest.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/BanSelfStudyServiceTest.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/CancelSelfStudyServiceTest.kt
💡 개요
- 학생정보 어드민 API에 캐시 기능을 추가했습니다.
📃 작업내용
- 학생정보 리스트 조회 로직에 Look Aside 읽기 캐시 전략 적용 및 리스트 내 정보가 변경될 수 있는 API 관련 로직에 Write Around 쓰기 전략을 적용했습니다.
- Look Aside 전략은 데이터를 읽을 때 먼저 캐시를 확인하여 캐시에 데이터가 존재하면 캐시에서 데이터를 읽어오고 만약 레디스에 찾는 데이터가 없다면 DB에 접근하여 데이터를 직접 가져와 레디스에 저장하는 방식입니다.
- Write Around 전략은 기본적으로 모든 데이터는 DB에 저장 후 Cache miss가 발생하는 경우에만 DB와 캐시에도 데이터를 저장하는 방식입니다.
- 데이터 변경 사항이 발생했을 시에 동시성 문제를 해결하기 위해서는 CachePut ( 부분 캐시 수정 ), CacheEvict ( 전체 캐시 데이터 삭제 ) 두 어노테이션을 사용할 수 있었습니다. 이 중 처음에는 CachePut 을 사용하려고 했지만 현재 캐시 기능을 도입하는 학생 정보 API 같은 경우에는 리스트 형식으로 저장이 이루어지기 때문에 부분 수정 방식을 사용할 수 없어 CacheEvict 를 통한 전체 삭제 방식을 사용했습니다.
=> #345 학생정보 어드민 API에 캐시 기능 추가

src/main/kotlin/com/dotori/v2/domain/auth/service/impl/SignUpServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/DeleteProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UpdateProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UploadProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/WithdrawalServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/ApplySelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/BanSelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/CancelBanSelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/CancelSelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/student/presentation/data/res/FindAllStudentResDto.kt, src/main/kotlin/com/dotori/v2/domain/student/service/impl/FindAllMemberServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/student/service/impl/ModifyStudentInfoServiceImpl.kt, src/main/kotlin/com/dotori/v2/global/config/RedisCacheConfig.kt, src/main/kotlin/com/dotori/v2/global/config/redis/service/RedisCacheService.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/ApplySelfStudyServiceSynchronicityTest.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/ApplySelfStudyServiceTest.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/BanSelfStudyServiceTest.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/CancelSelfStudyServiceTest.kt
💡 개요
- 학생정보 어드민 API에 캐시 기능을 추가했습니다.
📃 작업내용
- 학생정보 리스트 조회 로직에 Look Aside 읽기 캐시 전략 적용 및 리스트 내 정보가 변경될 수 있는 API 관련 로직에 Write Througt 쓰기 전략을 적용했습니다.
=> 학생정보 어드민 API에 캐시 기능 추가

src/main/kotlin/com/dotori/v2/domain/member/exception/NotAcceptImgExtensionException.kt, src/main/kotlin/com/dotori/v2/domain/member/service/ProfileImageService.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UpdateProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UploadProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/global/error/ErrorCode.kt
💡 개요
이미지 업로드시 서버단에서 확장자 검사를 하지않아 파일 업로드 공격이 가능합니다.
이미지 업로드 비즈니스 로직에서 파일 확장자 검사를 진행하는 로직을 추가하였습니다.
#356 
📃 작업내용
- 프로필 이미지를 업로드하는 서비스 로직인 `UpdateProfileImageServiceImpl`, `UploadProfileImageServiceImpl`에 확장자 검사 로직을 추가하였습니다. c1a08ebe037b7d8c50a5f1a69ce2f728157efd22
- 허용하는 확장자는 임의로 `jpg`, `jpeg`, `png`로 제한 해두었습니다. 추가해야할 확장자가 있다면 수정하도록 하겠습니다.
🔀 변경사항
확장자 검사 로직을 추가하면서 중복되는 코드가 많이 발생하여 추상클래스를 도입해보았습니다. 해당 변경사항에 대해 이견이 있시면 말씀해주시면 걷어내도록 하겠습니다!
- 확장자 검사 로직을 추가하면서 `UpdateProfileImageServiceImpl`, `UploadProfileImageServiceImpl`에서 중복되는 부분이 많이 발생하였습니다. (파일 업데이트시 기존 파일을 제거하는 로직을 제외하고 동일한 로직으로 확인하였습니다.)
- 위의 두 클래스에서 `ProfileImageService`라는 추상클래스를 상속받도록 하여 `imageUpload` 메서드에서 중복되는 로직을 한번에 처리하도록 구현해보았습니다.
- `imageUpload` 메서드에서는 `isUpdate`라는 파라미터를 받아 기존 파일 삭제 여부를 받도록 구현하였습니다. …
=> 이미지 업로드시 확장자 vadliation 추가

src/main/kotlin/com/dotori/v2/domain/member/service/impl/UpdateProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UploadProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt, src/main/kotlin/com/dotori/v2/domain/music/schedule/MusicSchedule.kt, src/main/kotlin/com/dotori/v2/global/config/redis/service/RedisCacheService.kt, src/main/kotlin/com/dotori/v2/global/util/ProfileImageService.kt
💡 개요
음악 데이터를 매달 1일마다 두 달전 모든 데이터들이 삭제되는 스케쥴러입니다.
음악 데이터를 삭제함에 따라서 캐시도 걷어야하기 때문에 RedisCacheService에 캐시를 invalid하는 로직을 분리했습니다.
=> 음악 데이터 초기화 스케쥴링

src/main/kotlin/com/dotori/v2/domain/selfstudy/properties/SelfStudyProperties.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/util/ValidDayOfWeekAndHourUtil.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/util/ValidaDayOfWeekAndHourTest.kt
💡 개요
profile이 dev일 때 자습신청이 "00:00-23:59"시에 모두 가능하도록 변경했습니다.
📃 작업내용
`ValidDayOfWeekAndHourUtil` 에서 selfStudyProperties값에 따라 자습신청을 다르게 제한하도록 작업하였습니다
🔀 변경사항
`application-dev.yml`, `application-prod.yml`에 self-study allowedTime 설정을 추가하였습니다
=> update :: self-study time

src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/GetSelfStudyInfoServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/util/ValidDayOfWeekAndHourUtil.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/GetSelfStudyInfoServiceTest.kt
💡 개요
자습신청 info api 에서 500이 반환되는 에러 해결
📃 작업내용
GetSelfStudyInfoServiceImpl의 `@Transactional` readOnly 설정을 해제하였습니다
=> Hotfix/selfstudy info 500에러 해결

src/main/kotlin/com/dotori/v2/domain/massage/domain/repository/MassageCountRepository.kt, src/main/kotlin/com/dotori/v2/domain/massage/service/impl/GetMassageInfoServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/massage/util/FindMassageCountUtil.kt, src/main/kotlin/com/dotori/v2/domain/massage/util/ValidDayOfWeekAndHourMassageUtil.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/domain/repository/SelfStudyCountRepository.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/GetSelfStudyInfoServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/util/FindSelfStudyCountUtil.kt, src/test/kotlin/com/dotori/v2/domain/massage/service/GetMassageInfoServiceTest.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/util/FindSelfStudyCountUtilTest.kt
💡 개요
select, select for update 쿼리 분리
📃 작업내용
- SelfStudy, Massage Service의 조회 API readonly 옵션 적용 롤백
- JPQL pessmistic lock(select for update 적용
=> 392 selfstudycount pessmistic

src/main/kotlin/com/dotori/v2/domain/music/presentation/data/res/MusicLikeCountResDto.kt
💡 개요
dto 필드에 private 접근제어자 때문에 {} 만 반환되고 값은 반환되지 않고 있어서 접근제어자 삭제 했습니다.
📃 작업내용
- dto 필드에 private 삭제
=> Music 좋아요, 좋아요 취소 시 현재 좋아요 수 반환 안됨

src/main/kotlin/com/dotori/v2/domain/auth/service/impl/SignUpServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/DeleteProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UpdateProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/UploadProfileImageServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/member/service/impl/WithdrawalServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/ApplySelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/BanSelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/CancelBanSelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/domain/selfstudy/service/impl/CancelSelfStudyServiceImpl.kt, src/main/kotlin/com/dotori/v2/global/config/redis/service/RedisCacheService.kt, src/main/kotlin/com/dotori/v2/global/util/ProfileImageService.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/ApplySelfStudyServiceSynchronicityTest.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/ApplySelfStudyServiceTest.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/BanSelfStudyServiceTest.kt, src/test/kotlin/com/dotori/v2/domain/selfstudy/service/CancelSelfStudyServiceTest.kt
💡 개요
- 회원가입/탈퇴, 유저 프로필 설정, 자습 관련 코드에 캐시 관련 기능 및 캐시 데이터의 TTL 설정을 추가했습니다.
📃 작업내용
- 회원가입/탈퇴, 유저 프로필 설정, 자습 관련 코드가 실행될 때 기존에 memberList 캐시 데이터를 저장 중이라면 해당 데이터를 걷어내는 기능을 구현했습니다.
- memberList 캐시 데이터의 TTL을 1시간으로 설정하는 코드를 추가했습니다.
=> 회원가입/탈퇴, 유저 프로필 설정, 자습 관련 코드에 캐시 관련 기능 추가

src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicLikeRepository.kt, src/main/kotlin/com/dotori/v2/domain/music/domain/repository/MusicRepository.kt, src/main/kotlin/com/dotori/v2/domain/music/schedule/MusicSchedule.kt
💡 개요
2달에 한번씩 음악 데이터를 삭제하는 플로우를 조정했습니다.
📃 작업내용
아래와 같은 flow로 진행됩니다.
- 2달전 음악을 불러온다.
- 해당 음악에 속한 좋아요 정보들을 모두 삭제한다.
- 불러온 음악을 모두 삭제한다.
=> 451 hotfix 음악 삭제 스케쥴 플로우 조정

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, src/main/kotlin/com/dotori/v2/domain/music/listener/MusicApplicationEventListener.kt, src/main/kotlin/com/dotori/v2/domain/reserve/ReserveEventListener.kt, src/main/kotlin/com/dotori/v2/global/async/AsyncConfig.kt, src/main/kotlin/com/dotori/v2/global/config/config/ConfigurationPropertiesScanConfig.kt, src/main/kotlin/com/dotori/v2/global/config/redis/RedisCacheConfig.kt, src/main/kotlin/com/dotori/v2/global/config/retry/RetryConfig.kt, src/main/kotlin/com/dotori/v2/global/config/schedule/EnableSchedulingConfig.kt, src/main/kotlin/com/dotori/v2/global/publisher/SQSEventPublisher.kt
**sqs event를 발행할때 실패하게 되면 3번 2 4 8초 간격으로 재시도합니다.**
dotori내에서 `MessageDuplicationId`를 생성하고 있기 때문에 sourcing할 이벤트는 중복되지 않습니다.
sqs 내의 aws DLQ 구성을 설정해 재시도에서도 실패한 메시지를 처리합니다. 
squirrel sqs는 한대이므로 visibility timeout은 따로 설정하지 않았습니다.
=> SQS Event Publish Retry
